### ISSUE TITLE
Bitkey compile fails from SSH and from console

### ISSUE THREAD

**Issue by dukewins** [bitkey/bitkey#39] opened 2017-06-13 01:43 UTC
README.rst says:
    BitKey is built with TKLDev, the TurnKey GNU/Linux build system.
  1. Deploy TKLDev (e.g., as a local VM)
  2. SSH into TKLDev and clone bitkey git repo:
    ssh tkldev
    cd products
    git-clone https://github.com/bitkey/bitkey
    cd bitkey
    make

Using a VirtualBox (5.0.10) host in Windows 7, I imported 
turnkey-tkldev-14.1-jessie-amd64.ova
with a live internet connection so it could do its downloads.

First, I logged in on the console and entered
`    cd /turnkey/fab/products`
`    git-clone https://github.com/bitkey/bitkey`
`    cd bitkey`
`    make`

The result was (starting at line 10 of a 13-line traceback):
`    executil.ExecError: non-zero exitcode(1) for command: useraufs-mount '--udba=reval'  'build/bootstrap'  '/turnkey/fab/bootstraps/jessie' `
`    Fatal: configuration disallows operations involving directory 'build/bootstrap' `
`    /usr/share/fab/product.mk:476 recipe for target 'build/stamps/bootstrap' failed `

Next, I moved to openSUSE where SSH is readily available, reimported the .ova file, and used SSH to access the VM.  Note that I had not yet logged in via the console.  SSH dropped me into /root so the same command sequence should have worked.  

The result was:
`    Makefile:13: /turnkey/fab/common/mk/turnkey-desktop.mk: No such file or directory `
`    make: *** No rule to make target '/turnkey/fab/common/mk/turnkey-desktop.mk'.  Stop. `
Inspection shows that /turnkey/fab/common does not exist.

Please explain how to circumvent these problems and make a successful compile in either Windows 7 or openSUSE.

Thanks!

**Comment by JedMeister** [comment] 2017-06-13 03:25
Hmm, sounds weird... Your initial try using VirtualBox should have worked. I'll launch a new TKLDev and see if I can recreate the issue. Also FWIW, if you're running windows, then [PuTTY](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html) is probably the best option for SSH.

Your second failure on openSUSE is to be expected. TKLDev contains lots of bits and pieces and it looks like you haven't manually downloaded/included them all. Also seeing as TurnKey is Debian based, even if you did have all the bits in place, I'm still not sure it'd work anyway.

I've launched a new TKLDev instance to see if I can recreate your issue. I'll post back with my results (and hopefully a workaround if I can confirm).

**Comment by dukewins** [comment] 2017-06-13 04:09
Thanks very much for the quick response!  I don't understand why an openSUSE **host** will change how your TKLDev **guest** works inside its own VM.  Maybe I didn't make it clear enough that I again imported your turnkey-tkldev-14.1-jessie-amd64.ova into a VM, the second time hosted by openSUSE.  I was surprised that I got a different error, and that the other directories under /turnkey/fab were present in the TKLDev VM hosted by Windows, but absent in the TKLDev VM hosted by openSUSE.  I did not rerun the Windows case to find out _when_ those other directories were created.

From my perspective, the fundamental difference was that I ran the compile attempt with the Windows host directly from the command line in the VM; but in the openSUSE host, I ran it through SSH.  The TKLDev VMs should have been identical, since both were spawned from your .ova.

**Comment by JedMeister** [comment] 2017-06-13 04:24
Sorry, I misunderstood... I thought you were trying to use openSUSE as the base...

You are right, it shouldn't matter what OS the host is using, so long as it supports 64 bit guest OS it should just work...

FWIW I just launched a fresh TKLDev. I completed the inithooks normally (including installing sec updates) and then SSHed in (it shouldn't matter but FWIW I use Debian as my desktop). I then ran the commands (same as you):
````
cd products
git-clone https://github.com/bitkey/bitkey
cd bitkey
make
````
and I couldn't reproduce either of your issues?!? It all just worked...! So TBH, I'm not really sure what might be the issue?!

The missing directories (on the openSUSE host) would occur if the `tkldev-setup` script failed. You could try manually re-running it perhaps? 

The error on your Windows host I've never seen before though! I have no idea on that one but it certainly seems like there is something funky going on...

Did you verify the OVA from the hash file? It shouldn't really matter as the OVA has a checksum file built in and should error on import if it the vHDD doesn't match the checksum, but it's the only other thing I can think of.

**Comment by dukewins** [comment] 2017-06-13 05:34
You solved it!  In the openSUSE host, I ran **tkldev-setup** and saw scripts I have not seen before, then ran **make** and it completed normally, resulting in a _product.iso_ with a length of 544210944.

Thanks again!  I consider this issue closed, but I won't press the "Close and comment" button because I want to experiment some more and see if I can identify what I was doing that caused those error messages.  If "Close and comment" means I can't add more comments, please leave it open a few days.

**Comment by JedMeister** [comment] 2017-06-13 06:38
Great news. I'll close it, but we can reopen it (or worst case open a new one).

**Closed as completed by JedMeister** 2017-06-13 06:38 UTC
